packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

source "googlecompute" "autogenerated_1" {
  project_id          = "dev-assignment4"
  source_image_family = "centos-stream-8"
  ssh_username        = "packer"
  zone                = "us-central1-a"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]


  provisioner "file" {
    source      = "webapp2.zip"
    destination = "~/webapp2.zip"
  }


  provisioner "shell" {
    script  = "script.sh"
  }

    provisioner "shell" {
    scripts = [
      "systemd.sh",
    ]
  }

}
