name: DB and Integration Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Db setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: setup Node.js
        uses: actions/setup-node@v3

      - name: Create env file,
        run: |
          echo "MYSQL_HOSTNAME=${{secrets.MYSQL_HOSTNAME}}" >> .env
          echo "MYSQL_DATABASENAME=${{secrets.MYSQL_DATABASENAME}}" >> .env
          echo "MYSQL_USERNAME=${{secrets.MYSQL_USERNAME}}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}" >> .env
          cat .env

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl status MySQL

      - name: create db
        run: mysql -u ${{secrets.MYSQL_USERNAME}} -p"${{secrets.MYSQL_ROOT_PASSWORD}}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASENAME }};" || exit 1 

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test