name: build.js

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/checkout@v3
        with:
          node-version: "v21.2.0"

      - name: Install dependencies
        run: npm install

      - name: Install mysql
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server
          sudo apt-get install mysql-client
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Create the db and apply the same
        run: |
          mysql -u${{secrets.MYSQL_USERNAME}} -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "CREATE DATABASE IF NOT EXISTS ${{secrets.MYSQL_DATABASENAME}};"
          mysql -u${{ secrets.MYSQL_USERNAME}} -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "USE ${{secrets.MYSQL_DATABASENAME}};"

      - name: Run The Test

        env:
          db_host: 127.0.0.1
          db_username: root
          db_password: root
          db_database: ${{secrets.MYSQL_DATABASENAME}}
          test: ci_testing

        run: |
          npm test

      - name: Delete the db
        run: |
          mysql -u${{secrets.MYSQL_USERNAME}} -p${{secrets.MYSQL_ROOT_PASSWORD}} -e "DROP DATABASE ${{secrets.MYSQL_DATABASENAME}}"

      - name: All tests completed
        run: echo "Test succesfull."
