name: Packer Build

# on:
#   push:
#     branches: [main]

on: [pull_request]

jobs:
  packer_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip Web App

      run: zip -r webapp.zip ../webapp



    - name: Set up Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.8.3/packer_1.8.3_linux_amd64.zip
        unzip packer_1.8.3_linux_amd64.zip
        chmod +x packer
        sudo mv packer /usr/local/bin/
      shell: bash

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
        unzip packer_1.7.2_linux_amd64.zip
        chmod +x packer
        mv packer /usr/local/bin
      shell: bash

    - name: Run packer init
      run: packer init packer-file.json.pkr.hcl
    
    - name: Run `packer Build`
      id: packer_build
      run: |
        echo "Running packer build"

    - name: Create new Instance Template
      run: |
        gcloud beta compute instance-templates create webapp-template-new --project=dev-assignment4 --description=Webapp\ instance\ template. --machine-type=e2-medium --network-interface=subnet=new-vpc-webapp,no-address --instance-template-region=projects/dev-assignment4/regions/us-central1 --metadata=startup-script=sudo\ bash\ \<\<EOF$'\n'cat\ \<\<INNER_EOF\ \|\ sudo\ tee\ /opt/csye6225/webapp/.env\ \>\ /dev/null$'\n'db_host=10.201.0.2$'\n'db_username=webapp$'\n'db_password=X0v1Rtx9$'\n'db_database=webapp$'\n'INNER_EOF$'\n'EOF$'\n' --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=service-account-1@dev-assignment4.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.read --region=us-central1 --tags=new-vpc-webapp,load-balancer-backend,allow-health-check,http-server,https-server,lb-health-check --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image=projects/dev-assignment4/global/images/myimage4,mode=rw,size=20,type=pd-standard --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
    - name: Update the managed Instance Group
      run: |
        gcloud compute instance-groups managed rolling-action start-update webappserver-igm \ --version=template=webapp-template-new [--zone=["us-central1-a", "us-central1-f"] | --region=us-central1]